# Generated by Django 4.0.4 on 2022-07-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_sequencelabelingproject_use_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentdetectionandslotfillingproject',
            name='allow_overlapping',
            field=models.BooleanField(default=False),
        ),
    ]
