# Generated by Django 4.0.4 on 2022-07-11 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_sequencelabelingproject_use_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDocumentClassificationProject',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.project')),
                ('allow_overlapping', models.BooleanField(default=False)),
                ('grapheme_mode', models.BooleanField(default=False)),
                ('use_relation', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('projects.project',),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('DocumentClassification', 'document classification'), ('SequenceLabeling', 'sequence labeling'), ('Seq2seq', 'sequence to sequence'), ('IntentDetectionAndSlotFilling', 'intent detection and slot filling'), ('Speech2text', 'speech to text'), ('ImageClassification', 'image classification'), ('Custom', 'custom document classification')], max_length=30),
        ),
    ]
