# Generated by Django 4.0.4 on 2022-12-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_customdocumentclassificationproject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdocumentclassificationproject',
            name='shared_org_label',
            field=models.BooleanField(default=False),
        ),
    ]
