# Generated by Django 4.0.4 on 2022-10-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_affectiveannotationproject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectiveannotationproject',
            name='is_single_ann_view',
            field=models.BooleanField(default=True),
        ),
    ]
