# Generated by Django 4.0.4 on 2022-11-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_affectiveannotationproject_is_single_ann_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectiveannotationproject',
            name='is_combination_mode',
            field=models.BooleanField(default=False),
        ),
    ]
