# Generated by Django 4.0.4 on 2023-02-20 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_dynamicannotationproject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicAnnotationProject',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.project')),
                ('allow_overlapping', models.BooleanField(default=False)),
                ('grapheme_mode', models.BooleanField(default=False)),
                ('use_relation', models.BooleanField(default=False)),
                ('is_summary_mode', models.BooleanField(default=False)),
                ('is_emotions_mode', models.BooleanField(default=False)),
                ('is_offensive_mode', models.BooleanField(default=False)),
                ('is_humor_mode', models.BooleanField(default=False)),
                ('is_others_mode', models.BooleanField(default=False)),
                ('is_single_ann_view', models.BooleanField(default=True)),
                ('is_combination_mode', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('projects.project',),
        ),
        migrations.AddField(
            model_name='dimensionmetadata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dimensionmetadata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dynamicdimension',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dynamicdimension',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dimensionmetadata',
            name='codename',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dimensionmetadata',
            name='dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_meta_data', to='projects.dynamicdimension'),
        ),
        migrations.AlterField(
            model_name='dimensionmetadata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dynamicdimension',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dynamicdimension',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dynamicdimension',
            name='type',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='ProjectDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dimension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.dynamicdimension')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='projects.project')),
            ],
        ),
    ]
