# Generated by Django 4.0.4 on 2023-03-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_dynamicannotationproject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dimensionmetadata',
            old_name='value',
            new_name='config',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('DocumentClassification', 'document classification'), ('SequenceLabeling', 'sequence labeling'), ('Seq2seq', 'sequence to sequence'), ('IntentDetectionAndSlotFilling', 'intent detection and slot filling'), ('Speech2text', 'speech to text'), ('ImageClassification', 'image classification'), ('ArticleAnnotation', 'article annotation'), ('AffectiveAnnotation', 'affective annotation'), ('DynamicAnnotation', 'dynamic annotation')], max_length=30),
        ),
    ]
