# Generated by Django 4.0.4 on 2023-03-21 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_projectdimension_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dimensionmetadata',
            unique_together={('dimension', 'codename')},
        ),
        migrations.AlterUniqueTogether(
            name='dynamicdimension',
            unique_together={('name', 'type')},
        ),
    ]
