# Generated by Django 4.0.4 on 2023-03-21 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_dimensionmetadata_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dimensionmetadata',
            unique_together={('id', 'codename')},
        ),
    ]
