# Generated by Django 4.0.4 on 2023-03-21 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_dimensionmetadata_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dimensionmetadata',
            unique_together={('dimension', 'codename')},
        ),
    ]
