# Generated by Django 4.0.4 on 2023-03-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_dimensionmetadata_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dimensionmetadata',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='dynamicdimension',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='dimensionmetadata',
            name='codename',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='dynamicdimension',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
