# Generated by Django 4.0.4 on 2023-03-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_dimensionmetadata_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicannotationproject',
            name='package_data_type',
            field=models.BooleanField(default=False),
        ),
    ]
