# Generated by Django 4.0.4 on 2022-09-29 14:25

from django.db import migrations, models
import django.db.models.deletion


def populate_questionnaire_types(apps, schema_editor):
    questionnaire_types = [
        "Przed badaniem",
        "Przed i po badaniu",
        "Po pierwszym tygodniu i na końcu badań",
        "Codziennie w trakcie badania",
        "Ankieta na koniec badania",
        "Ankieta po 2 tygodniach badania",
    ]
    description = [""]*len(questionnaire_types)
    QuestionnaireType = apps.get_model('questionnaires', 'QuestionnaireType')
    for i in range(len(questionnaire_types)):
        object = QuestionnaireType(name=questionnaire_types[i], description=description[i])
        object.save()

def populate_questionnaires(apps, schema_editor):
    questionnaires = [
        "IPIP-BFM-20 (Osobowość)",
        "Demografia",
        "Humor Styles Questionnaire",
        "SWLS-A (Dobrostan: Satysfakcja z życia)",
        "SPANE (Dobrostan: Afekt)",
        "Dobrostan: Skala Prosperowania",
        "PHQ-9 (Depresja: Kwestionariusz Zdrowia Pacjenta)",
        "PSS (Stres)",
        "Physical Health Questionnaire (Zdrowie)",
        "RESS-EMA (Regulacja emocji)",
        "PAQ (Aleksytymia)",
        "Ankieta zwrotna",
        "Sen (rano)",
        "Stres (rano)",
        "Stres (wieczorem)",
        "Zdrowie (wieczorem)",
        "Emocje (w przerwie)",
        "Anotacja (na koniec badania)",
        "Ankieta po 2 tygodniach badania",
    ]
    description = [""]*len(questionnaires)
    questionnaire_type = [1]*3 + [2]*8 + [3] + [4]*5 + [5, 6]
    language = ["pl"]*len(questionnaires)
    time_of_day = [""]*12 + ["rano"]*2 + ["wieczorem"]*2 + ["w przerwie"] + ["", ""]
    Questionnaire = apps.get_model('questionnaires', 'Questionnaire')
    for i in range(len(questionnaires)):
        object = Questionnaire(name=questionnaires[i], description=description[i], questionnaire_type_id=questionnaire_type[i], language=language[i], time_of_day=time_of_day[i])
        object.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=1024)),
                ('language', models.CharField(max_length=1024)),
                ('time_of_day', models.CharField(max_length=1024)),
                ('questionnaire_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaires.questionnairetype')),
            ],
        ),
        migrations.RunPython(populate_questionnaire_types),
        migrations.RunPython(populate_questionnaires),
    ]
