# Generated by Django 4.0.4 on 2022-09-29 14:25

from django.db import migrations, models

def populate_questionnaire_types(apps, schema_editor):
    questionnaire_types = [
        "Przed badaniem",
        "Przed i po badaniu",
        "Po pierwszym tygodniu i na końcu badań",
        "Codziennie w trakcie badania",
        "Ankieta na koniec badania",
        "Ankieta po 2 tygodniach badania",
    ]
    description = [
        "",
        "",
        "",
        "",
        "",
        ""
    ]
    QuestionnaireType = apps.get_model('questionnaires', 'QuestionnaireType')
    for i in range(len(questionnaire_types)):
        object = QuestionnaireType(name=questionnaire_types[i], description=description[i])
        object.save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.RunPython(populate_questionnaire_types),
    ]
