# Generated by Django 4.0.4 on 2022-09-29 14:25

from django.db import migrations, models
import django.db.models.deletion


def populate_questions(apps, schema_editor):
    ipip_bfm_questions = [
        "Jestem duszą towarzystwa.",
        "Niezbyt obchodzą mnie inni ludzie.",
        "Zostawiam moje rzeczy gdzie popadnie.",
        "Zwykle jestem zrelaksowany/a.",
        "Mam bogate słownictwo.",
        "Trzymam się z boku.",
        "Jestem wyrozumiały/a dla uczuć innych ludzi.",
        "Bez zwłoki wypełniam codzienne obowiązki.",
        "Często martwię się czymś.",
        "Mam trudności ze zrozumieniem abstrakcyjnych pojęć.",
        "Rozmawiam z wieloma różnymi ludźmi na przyjęciach.",
        "Nie interesują mnie problemy innych ludzi.",
        "Często zapominam odkładać rzeczy na miejsce.",
        "Rzadko czuję się przygnębiony/a.",
        "Mam głowę pełną pomysłów.",
        "Wśród nieznajomych jestem małomówny/a.",
        "Znajduję czas dla innych.",
        "Postępuję zgodnie z harmonogramem.",
        "Często miewam huśtawki nastrojów.",
        "Nie mam zbyt bogatej wyobraźni.",
    ]
    demografia_questions = [
        "[Płeć / Gender]",
        "[Wiek]",
        "[Narodowość]",
        "[Język]",
        "[Dzieci]",
        "[Opieka]",
        "[Dochody]",
        "[Sektor zatrudnienia]",
        "[Status związku]",
        "[Wielkość gospodarstwa domowego]",
        "[Wykształcenie]",
        "[Obecnie studiujesz]",
        "[Zatrudnienie]",
        "[Religia]",
        "[Poglądy polityczne]",
        "Oś ekonomiczna",
        "Oś światopoglądowa/społeczna:"
    ]
    humor_styles_questions = [
        "Rzadko śmieję się lub żartuję z innymi ludźmi.",
        "Gdy czuję się przygnębiony(a), zazwyczaj potrafię sam(a) się rozweselić.",
        "Jeżeli ktoś popełni błąd, wypowiadam uszczypliwą uwagę.",
        "Bardziej niż powinienem/powinnam, pozwalam ludziom śmiać się ze mnie lub bawić się moim kosztem.",
        "Nie sprawia mi dużej trudności rozśmieszenie innych. Wydaje mi się, że jestem osobą obdarzoną naturalnym poczuciem humoru.",
        "Nawet kiedy jestem sam(a), często rozśmieszają mnie absurdalne sytuacje życiowe.",
        "Ludzie nigdy nie czują się urażeni ani dotknięci moim poczuciem humoru.",
        "Często przesadzam w ośmieszaniu siebie, jeżeli bawi to moją rodzinę lub przyjaciół.",
        "Rzadko rozśmieszam innych, opowiadając zabawne historyjki o sobie",
        "Jeżeli jestem zmartwiony(a) lub czuję się nieszczęśliwy(a), zazwyczaj staram się znaleźć coś zabawnego w tej sytuacji, aby poprawić sobie humor.",
        "Opowiadając dowcipy lub zabawne historie, zazwyczaj nie zastanawiam się nad tym czy ktoś poczuje się dotknięty/urażony.",
        "Często staram się sprawić, aby ludzie bardziej polubili lub zaakceptowali mnie poprzez opowiadanie zabawnych rzeczy o własnych słabościach, gafach lub błędach.",
        "Dużo śmieję się i często żartuję w gronie moich najbliższych przyjaciół.",
        "Moje pełne humoru spojrzenie na życie sprawia, że mniej martwię się różnymi sprawami.",
        "Nie podoba mi się kiedy ktoś wykorzystuje humor w celu ośmieszania lub poniżania innych.",
        "Rzadko mówię zabawne rzeczy, które mogłyby mnie ośmieszyć.",
        "Zazwyczaj nie lubię opowiadać dowcipów ani rozśmieszać ludzi.",
        "Kiedy jestem sam(a) i czuję się nieszczęśliwy(a), staram się myśleć o czymś zabawnym, aby poprawić sobie humor.",
        "Czasami kiedy myślę o czymś zabawnym, nie mogę się powstrzymać od opowiedzenia o tym, nawet jeśli wiem, że jest to niestosowne w danej sytuacji.",
        "Często przekraczam granicę w ośmieszaniu siebie, kiedy opowiadam dowcipy lub staram się być zabawny(a).",
        "Sprawia mi przyjemność rozśmieszanie ludzi.",
        "Zazwyczaj, kiedy jestem smutny(a), tracę poczucie humoru.",
        "Nigdy nie wyśmiewam się z innych, nawet jeśli robią to moi przyjaciele.",
        "Kiedy jestem ze znajomymi lub rodziną często mam wrażenie, że to ze mnie się śmieją lub żartują.",
        "Rzadko wygłupiam się z moimi przyjaciółmi.",
        "Z doświadczenia wiem, że myślenie o jakimś zabawnym aspekcie sytuacji często jest bardzo dobrym sposobem radzenia sobie z problemami.",
        "Jeśli kogoś nie lubię często posługuję się żartem lub kpiną aby go ośmieszyć lub poniżyć.",
        "Jeśli mam problemy lub czuję się nieszczęśliwy(a), często ukrywam to żartując i nawet moi najbliżsi przyjaciele nie wiedzą co naprawdę czuję.",
        "Zazwyczaj nie przychodzi mi do głowy nic zabawnego, kiedy jestem w towarzystwie innych ludzi.",
        "Nie potrzebuję towarzystwa innych ludzi, aby czuć się rozbawiony(a) – zazwyczaj znajduję powody do śmiechu nawet, kiedy jestem sam(a).",
        "Nawet jeśli coś jest dla mnie bardzo zabawne nie będę się z tego śmiać ani żartować jeśli wiem, że może to kogoś urazić.",
        "Pozwalanie innym na śmianie się ze mnie jest sposobem na utrzymanie moich przyjaciół i rodziny w dobrym nastroju.",
    ]
    swlsa_questions = [
        "Pod wieloma względami moje życie jest zbliżone do ideału.",
        "Warunki mojego życia są doskonałe.",
        "Jestem zadowolony/a z mojego życia.",
        "W życiu osiągnąłem/osiągnęłam najważniejsze rzeczy, które chciałem/am.",
        "Gdybym mógł/mogła jeszcze raz przeżyć swoje życie, to nie chciałbym/chciałabym prawie nic zmienić.",
    ]
    spane_questions = [
        "Pozytywnie",
        "Negatywnie",
        "Dobrze",
        "Źle",
        "Przyjemnie",
        "Nieprzyjemnie",
        "Szczęśliwy/-a",
        "Smutny/-a",
        "Przestraszony/-a",
        "Radosny/-a",
        "Rozgniewany/-a",
        "Zadowolony/-a",
    ]
    skala_questions = [
        "Prowadzę życie, które ma sens i cel.",
        "Moje relacje społeczne są wspierające i dają mi satysfakcję.",
        "Angażuję się i interesuję tym, czym zajmuję się na co dzień.",
        "Aktywnie przyczyniam się do szczęścia i dobrostanu innych.",
        "Jestem kompetentny i zdolny do wykonywania zajęć, które są dla mnie ważne.",
        "Jestem dobrym człowiekiem i prowadzę dobre życie.",
        "Z optymizmem patrzę na swoją przyszłość.",
        "Ludzie mnie szanują.",
    ]
    phq9_questions = [
        "Niewielkie zainteresowanie lub odczuwanie przyjemności z wykonywania czynności.",
        "Uczucie smutku, przygnębienia lub beznadziejności.",
        "Kłopoty z zaśnięciem lub przerywany sen, albo zbyt długi sen.",
        "Uczucie zmęczenia lub brak energii.",
        "Brak apetytu lub przejadanie się.",
        "Poczucie niezadowolenia z siebie — lub uczucie, że jest się do niczego, albo że zawiódł/zawiodła Pan/Pani siebie lub rodzinę.",
        "Problemy ze skupieniem się na przykład przy czytaniu gazety lub oglądaniu telewizji.",
        "Poruszanie się lub mówienie tak wolno, że inni mogliby to zauważyć? Albo wręcz przeciwnie — niemożność usiedzenia w miejscu lub podenerwowanie powodujące ruchliwość znacznie większą niż zwykle.",
        "Myśli, że lepiej byłoby umrzeć, albo chęć zrobienia sobie jakiejś krzywdy.",
    ]
    pss_questions = [
        "Jak często w ciągu ostatniego miesiąca byłeś/aś zdenerwowany/a, ponieważ zdarzyło się coś niespodziewanego?",
        "Jak często w ciągu ostatniego miesiąca czułeś/aś, że ważne sprawy w twoim życiu wymykają ci się spod kontroli?",
        "Jak często w ciągu ostatniego miesiąca odczuwałeś/aś zdenerwowanie i napięcie?",
        "Jak często w ciągu ostatniego miesiąca byłeś/aś przekonany/a, że jesteś w stanie poradzić sobie z problemami osobistymi?",
        "Jak często w ciągu ostatniego miesiąca czułeś/aś, że sprawy układają się po twojej myśli?",
        "Jak często w ciągu ostatniego miesiąca stwierdzałeś/aś, że nie radzisz sobie ze wszystkimi obowiązkami?",
        "Jak często w ciągu ostatniego miesiąca potrafiłeś/aś opanować swoje rozdrażnienie?",
        "Jak często w ciągu ostatniego miesiąca czułeś/aś, że wszystko ci wychodzi?",
        "Jak często w ciągu ostatniego miesiąca złościłeś/aś się, ponieważ nie miałeś/aś wpływu na to co się zdarzyło?",
        "Jak często w ciągu ostatniego miesiąca czułeś/aś, że nie możesz przezwyciężyć narastających trudności?",
    ]
    zdrowie_questions = [
        "Jak często miałeś/aś trudności z zasypianiem w nocy?",
        "Jak często budziłeś/aś się w nocy?",
        "Jak często miałeś/aś koszmary senne lub niepokojące sny?",
        "Jak często Twój sen był spokojny i niezakłócony?",
        "Jak często miałeś/aś bóle głowy?",
        "Jak często bolała Cię głowa, gdy wywierano się na Ciebie dużą presję, aby załatwić sprawy?",
        "Jak często bolała Cię głowa, gdy byłeś/aś sfrustrowany/a, ponieważ sprawy nie ułożyły się tak, jak powinny, lub gdy byłeś/aś na kogoś zirytowany/a?",
        "Jak często cierpiałeś/aś z powodu rozstroju żołądka (niestrawności)?",
        "Jak często musiałeś/aś uważać na to, co jesz, aby uniknąć rozstroju żołądka?",
        "Jak często miałeś/aś mdłości lub inne problemy żołądkowe?",
        "Jak często miałeś/aś zaparcia lub cierpiałeś na biegunkę?",
        "Ile razy miałeś/aś drobne przeziębienie (np. takie które sprawiło, że czułeś/aś się niekomfortowo, ale nie zatrzymało Cię ono w łóżku ani nie spowodowało, że opuściłeś/aś pracę)?",
        "Ile razy miałeś/aś infekcje dróg oddechowych, poważniejsze niż drobne przeziębienie (np. takie które 'rozłożyły' cię na łopatki - zapalenie oskrzeli, zapalenie zatok itp.)?",
        "Jak długo na ogół trwało przeziębienie lub grypa, które przechodziłeś/aś?",
    ]
    ress_ema_questions = [
        "Starałem/am się zwolnić tętno i oddech.",
        "Wziąłem/am głęboki oddech.",
        "Okazałem/am swoje uczucia.",
        "Wyraziłem/am swoje uczucia.",
        "W kółko myślałem/am o tym wydarzeniu emocjonalnym.",
        "Ciągle myślałem/am o tym, co mi przeszkadzało.",
        "Myślałem/am o innych sposobach interpretacji sytuacji.",
        "Spojrzałem/am na sytuację z kilku różnych punktów widzenia.",
        "Zaangażowałem/am się w coś innego, żeby mieć zajęcie.",
        "Zaangażowałem/am się w jakieś czynności, żeby odwrócić swoją uwagę.",
        "Starałem/am się ukryć swoje uczucia.",
        "Udawałem/am, że wcale nie odczuwam emocji, którą odczuwałem/am.",
    ]
    paq_questions = [
        "Kiedy czuję się źle (odczuwam nieprzyjemne emocje), nie potrafię znaleźć odpowiednich słów, by opisać te uczucia.",
        "Kiedy czuję się źle, nie potrafię powiedzieć, czy jestem smutny, zły czy przestraszony.",
        "Mam skłonność do ignorowania tego, co czuję.",
        "Kiedy czuję się dobrze (odczuwam przyjemne emocje), nie potrafię znaleźć odpowiednich słów, by opisać te uczucia.",
        "Kiedy czuję się dobrze, nie potrafię powiedzieć, czy jestem szczęśliwy, podekscytowany czy rozbawiony.",
        "Nie zwracam uwagi na swoje emocje.",
    ]
    zwrotna_questions = [
        "Jak często powinno się robić przerwy w pracy anotacyjnej?",
        "Jak długie powinno się robić przerwy w pracy anotacyjnej?",
        "Co byś zmieniła/zmienił w ankiecie?"
    ]
    sen_questions = [
        "Jak oceniasz jakość swojego snu ostatniej nocy?",
        "Jak czułeś/aś się dziś rano?",
    ]
    stres_rano_questions = [
        "Czuję się zestresowany, niespokojny, przytłoczony.",
        "Czuję, że panuję nad sytuacją, dobrze sobie radzę, mam wszystko pod kontrolą.",
    ]
    stres_wieczor_questions = [
        "Czuję, że wszystko mnie teraz przytłacza.",
        "Czuję, że wszystko jest teraz nieprzewidywalne.",
    ]
    zdrowie_wieczor_questions = [
        "Jak oceniasz stan swojego zdrowia?",
        "Jak się dzisiaj czułeś/aś?"
    ]
    emocje_questions = [
        "Czy właśnie czułeś silną emocję?",
        "Jak się czułaś: Neg-Pos",
        "Jak się czułaś: Ospały-Bardzo pobudzony",
    ]
    anotacja_koniec_questions = [
        "Jak często powinno się robić przerwy w pracy anotacyjnej?",
        "Jak długie powinno się robić przerwy w pracy anotacyjnej?",
        "Czy któreś pytanie/polecenie dotyczące tekstu było niezrozumiałe?",
        "Jakimi słowami opisałbyś ten tekst (tagi, słowa kluczowe)? Dlaczego?",
        "Jakie wrażenia/emocje/odczucia wzbudza w Tobie ten tekst? Dlaczego?",
        "Czy tekst wzbudza w Tobie jakiekolwiek emocje? Dlaczego?",
        "etc? Dlaczego?",
        "Tekstów było?"
        "Jaka liczba tekstów byłaby odpowiednia?",
        "Co byś zmieniła/zmienił w badaniu?",
    ]
    ankieta_tygodniu_questions = [
        "Czy spotkanie na Google Meets było problematyczne?",
        "Czy wolałabyś/wolałbyś spotkanie na Zoom?",
        "Czy wolałabyś/wolałbyś spotkanie na innej platformie (jakiej)?",
        "Czy korzystałeś/korzystałaś z kontaktu z osobą odpowiedzialną za rozwiązywanie problemów i wsparcie?",
        "Czy masz jakieś pomysły/sugestie dotyczące webinarium?",
        "Jak często powinno się robić przerwy w pracy anotacyjnej?",
        "Jak długie powinno się robić przerwy w pracy anotacyjnej?",
        "Czy któreś pytanie/polecenie dotyczące tekstu było niezrozumiałe?",
        "Jakimi słowami opisałbyś ten tekst (tagi, słowa kluczowe)? Dlaczego?",
        "Jakie wrażenia/emocje/odczucia wzbudza w Tobie ten tekst? Dlaczego?",
        "Czy tekst wzbudza w Tobie jakiekolwiek emocje? Dlaczego?",
        "etc? Dlaczego?",
        "Tekstów było?"
        "Jaka liczba tekstów byłaby odpowiednia?",
        "Co byś zmieniła/zmienił w badaniu?",
    ]
    questions = ipip_bfm_questions + demografia_questions +  humor_styles_questions + swlsa_questions + spane_questions + skala_questions + phq9_questions + pss_questions + zdrowie_questions + ress_ema_questions + paq_questions + zwrotna_questions + sen_questions + stres_rano_questions + stres_wieczor_questions + zdrowie_wieczor_questions + emocje_questions + anotacja_koniec_questions + ankieta_tygodniu_questions
    questionnaire = [1]*len(ipip_bfm_questions) + [2]*len(demografia_questions) + [3]*len(humor_styles_questions) + [4]*len(swlsa_questions) + [5]*len(spane_questions) + [6]*len(skala_questions) + [7]*len(phq9_questions) + [8]*len(pss_questions) + [9]*len(zdrowie_questions) + [10]*len(ress_ema_questions) + [11]*len(paq_questions) + [12]*len(zwrotna_questions) + [13]*len(sen_questions) + [14]*len(stres_rano_questions) + [15]*len(stres_wieczor_questions) + [16]*len(zdrowie_wieczor_questions) + [17]*len(emocje_questions) + [18]*len(anotacja_koniec_questions) + [19]*len(ankieta_tygodniu_questions)

    Question = apps.get_model('questionnaires', 'Question')
    Questionnaire = apps.get_model('questionnaires', 'Questionnaire')
    for i in range(len(questions)):
        object = Question(question_text=questions[i], questionnaire=Questionnaire(questionnaire[i]))
        object.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionnaires', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=1024)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaires.questionnaire')),
            ],
        ),
        migrations.RunPython(populate_questions),
    ]
