# Generated by Django 4.0.4 on 2022-11-17 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnaires', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='language',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='time_of_day',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='questionnairetype',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionnairetype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaires.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('question', 'user', 'answer_text')},
            },
        ),
    ]
