# Generated by Django 4.0.4 on 2023-03-09 16:30

from django.db import migrations

def update_humor_style_questionnaire(apps, schema_editor):
    replace_map = {
        38: "Rzadko śmieję się lub żartuję z innymi ludźmi.",
        39: "Gdy czuję się przygnębiony(a), zazwyczaj potrafię sam(a) się rozweselić.",
        40: "Jeżeli ktoś popełni błąd, wypowiadam uszczypliwą uwagę.",
        41: "Bardziej niż powinienem/powinnam, pozwalam ludziom śmiać się ze mnie lub bawić się moim kosztem.",
        42: "Nie sprawia mi dużej trudności rozśmieszenie innych. Wydaje mi się, że jestem osobą obdarzoną naturalnym poczuciem humoru.",
        43: "Nawet kiedy jestem sam(a), często rozśmieszają mnie absurdalne sytuacje życiowe.",
        44: "Ludzie nigdy nie czują się urażeni ani dotknięci moim poczuciem humoru.",
        45: "Często przesadzam w ośmieszaniu siebie, jeżeli bawi to moją rodzinę lub przyjaciół.",
        46: "Rzadko rozśmieszam innych, opowiadając zabawne historyjki o sobie",
        47: "Jeżeli jestem zmartwiony(a) lub czuję się nieszczęśliwy(a), zazwyczaj staram się znaleźć coś zabawnego w tej sytuacji, aby poprawić sobie humor.",
        48: "Opowiadając dowcipy lub zabawne historie, zazwyczaj nie zastanawiam się nad tym czy ktoś poczuje się dotknięty/urażony.",
        49: "Często staram się sprawić, aby ludzie bardziej polubili lub zaakceptowali mnie poprzez opowiadanie zabawnych rzeczy o własnych słabościach, gafach lub błędach.",
        50: "Dużo śmieję się i często żartuję w gronie moich najbliższych przyjaciół.",
        51: "Moje pełne humoru spojrzenie na życie sprawia, że mniej martwię się różnymi sprawami.",
        52: "Nie podoba mi się kiedy ktoś wykorzystuje humor w celu ośmieszania lub poniżania innych.",
        53: "Rzadko mówię zabawne rzeczy, które mogłyby mnie ośmieszyć.",
        54: "Zazwyczaj nie lubię opowiadać dowcipów ani rozśmieszać ludzi.",
        55: "Kiedy jestem sam(a) i czuję się nieszczęśliwy(a), staram się myśleć o czymś zabawnym, aby poprawić sobie humor.",
        56: "Czasami kiedy myślę o czymś zabawnym, nie mogę się powstrzymać od opowiedzenia o tym, nawet jeśli wiem, że jest to niestosowne w danej sytuacji.",
        57: "Często przekraczam granicę w ośmieszaniu siebie, kiedy opowiadam dowcipy lub staram się być zabawny(a).",
        58: "Sprawia mi przyjemność rozśmieszanie ludzi.",
        59: "Zazwyczaj, kiedy jestem smutny(a), tracę poczucie humoru.",
        60: "Nigdy nie wyśmiewam się z innych, nawet jeśli robią to moi przyjaciele.",
        61: "Kiedy jestem ze znajomymi lub rodziną często mam wrażenie, że to ze mnie się śmieją lub żartują.",
        62: "Rzadko wygłupiam się z moimi przyjaciółmi.",
        63: "Z doświadczenia wiem, że myślenie o jakimś zabawnym aspekcie sytuacji często jest bardzo dobrym sposobem radzenia sobie z problemami.",
        64: "Jeśli kogoś nie lubię często posługuję się żartem lub kpiną aby go ośmieszyć lub poniżyć.",
        65: "Jeśli mam problemy lub czuję się nieszczęśliwy(a), często ukrywam to żartując i nawet moi najbliżsi przyjaciele nie wiedzą co naprawdę czuję.",
        66: "Zazwyczaj nie przychodzi mi do głowy nic zabawnego, kiedy jestem w towarzystwie innych ludzi.",
        67: "Nie potrzebuję towarzystwa innych ludzi, aby czuć się rozbawiony(a) – zazwyczaj znajduję powody do śmiechu nawet, kiedy jestem sam(a).",
        68: "Nawet jeśli coś jest dla mnie bardzo zabawne nie będę się z tego śmiać ani żartować jeśli wiem, że może to kogoś urazić.",
        69: "Pozwalanie innym na śmianie się ze mnie jest sposobem na utrzymanie moich przyjaciół i rodziny w dobrym nastroju.",
    }
    Question = apps.get_model('questionnaires', 'Question')
    for row in Question.objects.filter(questionnaire=3):
        row.question_text = replace_map[row.id]
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0006_questionnairestate'),
    ]

    operations = [
        migrations.RunPython(update_humor_style_questionnaire),
    ]
