# Generated by Django 4.0.4 on 2022-09-29 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0014_remove_uuid_null'),
    ]
