# Generated by Django 4.0.4 on 2022-09-30 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0015_textlabel_question'),
    ]
