# Generated by Django 4.0.4 on 2022-09-30 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0017_category_question_scale'),
    ]
