# Generated by Django 4.0.4 on 2022-10-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0018_alter_scale_question_alter_textlabel_question'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scale',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='scale',
            name='scale',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
