# Generated by Django 4.0.4 on 2022-10-06 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0019_alter_scale_unique_together_scale_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='textlabel',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
