# Generated by Django 4.0.4 on 2022-10-06 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0020_alter_textlabel_question'),
    ]
