# Generated by Django 4.0.4 on 2022-10-12 11:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label_types', '0008_scaletype_scaletype_label_types_scaletype_is_unique'),
        ('examples', '0014_alter_example_article_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labels', '0022_remove_scale_question'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scale',
            unique_together={('example', 'user', 'label')},
        ),
    ]
