# Generated by Django 4.0.4 on 2022-10-17 10:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examples', '0014_alter_example_article_id'),
        ('labels', '0023_alter_scale_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='textlabel',
            unique_together={('example', 'user', 'text', 'question')},
        ),
    ]
