# Generated by Django 4.0.4 on 2022-10-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0024_alter_textlabel_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textlabel',
            name='question',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
