export const RESEARCH_TIME_IN_MONTHS = 3
export const TEXT_BATCH_COUNT = 20
export const DATETIME_FORMAT_DDMMYYHHMMSS = "DD-MM-YYYY HH:mm:ss"
export const DATE_FORMAT_DDMMYYYY = "DD-MM-YYYY"
export const DATETIME_FORMAT_YYYYMMDDTHHMMSS = "YYYY-MM-DDTHH:mm:ss"
