# Generated by Django 4.0.4 on 2022-09-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0006_alter_example_upload_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='article_id',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='example',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
