# Generated by Django 4.0.4 on 2022-09-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0007_example_article_id_example_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='type',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
