# Generated by Django 4.0.4 on 2022-09-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0011_remove_example_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='text_type',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
