# Generated by Django 4.0.4 on 2022-09-12 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0012_example_text_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='example',
            old_name='text_type',
            new_name='type',
        ),
    ]
