# Generated by Django 4.0.4 on 2022-10-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0014_alter_example_article_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplestate',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
