# Generated by Django 4.0.4 on 2022-10-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0015_examplestate_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplestate',
            name='started_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
