# Generated by Django 4.0.4 on 2022-10-25 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0016_alter_examplestate_started_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examplestate',
            name='started_at',
        ),
    ]
