# Generated by Django 4.0.4 on 2022-10-12 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0022_remove_scale_question'),
        ('data_export', '0002_exportedscale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportedTextQuestion',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('labels.textlabel',),
        ),
    ]
