# Generated by Django 4.0.4 on 2022-09-28 09:41

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        # migrations.RunPython(populate_questions),
    ]
